---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs-and-structure:
    name: Repo sanity checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify key docs exist
        run: |
          test -f README.md
          test -f CONTRIBUTING.md
          test -f CODE_OF_CONDUCT.md
          test -f LICENSE
          test -f SECURITY.md
          test -f ROADMAP.md
          test -f TASKS.md
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
